language: go
go:
- "1.10"
install:
- make setup
script:
- make ci


addons:
apt:
  packages:
  # needed for the nfpm pipe:
  - rpm
  # needed for the snap pipe:
  - snapcraft

env:
- PATH=/snap/bin:$PATH

install:
- sudo snap install snapcraft --classic

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux